[theme]
font = "sans serif"
base="light"
primaryColor = "#27AE60"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F4F4F4"
textColor = "#333333"

[server]
headless = true

[browser]
gatherUsageStats = true
